import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = join(root, ".env");

function loadEnv() {
  if (!existsSync(envPath)) return {};
  const vars = {};
  for (const line of readFileSync(envPath, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    vars[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return vars;
}

const env = loadEnv();
const url = env.SUPABASE_URL ?? "";
const key = env.SUPABASE_PUBLISHABLE_KEY ?? "";
const enabled = Boolean(url && key);

const out = `// Generated by scripts/generate-config.mjs — do not edit
export const SUPABASE_URL = ${JSON.stringify(url)};
export const SUPABASE_PUBLISHABLE_KEY = ${JSON.stringify(key)};
export const SUPABASE_ENABLED = ${enabled};
`;

writeFileSync(join(root, "config.js"), out, "utf8");
console.log(`Wrote config.js (SUPABASE_ENABLED=${enabled})`);
